version: "3.4"

services:
  postgressDb:
    image: postgres
    container_name: postgressDb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_VOLUMES}:/var/lib/mysql"
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com.br"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "16543:80"
    volumes:
      - "${PGADMIN_VOLUMES}:/root/.pgadmin"
    networks:
      - postgres-network
    depends_on:
      - postgressDb     
     
networks:
  postgres-network:
    driver: bridge