global using _Architecture.Api.Extensions;
global using _Architecture.Application.Responses;
global using AutoMapper;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel;
global using System.Net.Mime;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using DomainWarningException = _Architecture.Domain.Abstractions.WarningException;
