global using Customers.Api;
global using Monolith.Extensions;
global using Microsoft.OpenApi.Models;
global using Monolith.Settings;
global using System.Text.Json.Serialization;
global using System.Text.Json;
global using _Architecture.Api.Middlewares;
global using Customers.Application;
global using Quartz;