// <auto-generated />
using System;
using Customer.Insfrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customer.Insfrastructure.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customer.Domain.Customers.Aggregates.CustomerOrders.Entities.CustomerOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_order_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("OrderState")
                        .HasColumnType("integer")
                        .HasColumnName("order_state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_customer_order");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_order_customer_id");

                    b.ToTable("customer_order", (string)null);
                });

            modelBuilder.Entity("Customer.Domain.Customers.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("_Shared.Domain.Entities.ConsumerEventLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_event_log_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("DateConsumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_consumed");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_consumer_event_log");

                    b.ToTable("consumer_event_log", (string)null);
                });

            modelBuilder.Entity("_Shared.Domain.Entities.IntegrationEventLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("integration_event_log_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type_name");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("header");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TimesSent")
                        .HasColumnType("integer")
                        .HasColumnName("times_sent");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateddate");

                    b.HasKey("Id")
                        .HasName("pk_integration_event_log");

                    b.ToTable("integration_event_log", (string)null);
                });

            modelBuilder.Entity("Customer.Domain.Customers.Aggregates.CustomerOrders.Entities.CustomerOrderEntity", b =>
                {
                    b.HasOne("Customer.Domain.Customers.Entities.CustomerEntity", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_order_customer_customer_id");

                    b.OwnsOne("_Shared.Domain.ValueObjects.MoneyValueObject", "OrderTotal", b1 =>
                        {
                            b1.Property<Guid>("CustomerOrderEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_order_id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("amount");

                            b1.HasKey("CustomerOrderEntityId");

                            b1.ToTable("customer_order");

                            b1.WithOwner()
                                .HasForeignKey("CustomerOrderEntityId")
                                .HasConstraintName("fk_customer_order_customer_order_customer_order_id");
                        });

                    b.Navigation("Customer");

                    b.Navigation("OrderTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("Customer.Domain.Customers.Entities.CustomerEntity", b =>
                {
                    b.OwnsOne("_Shared.Domain.ValueObjects.MoneyValueObject", "OrderLimit", b1 =>
                        {
                            b1.Property<Guid>("CustomerEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 4)
                                .HasColumnType("numeric(10,4)")
                                .HasColumnName("amount");

                            b1.HasKey("CustomerEntityId");

                            b1.ToTable("customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerEntityId")
                                .HasConstraintName("fk_customer_customer_customer_id");
                        });

                    b.OwnsOne("_Shared.Domain.ValueObjects.PersonNameValueObject", "Name", b1 =>
                        {
                            b1.Property<Guid>("CustomerEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("last_name");

                            b1.HasKey("CustomerEntityId");

                            b1.ToTable("customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerEntityId")
                                .HasConstraintName("fk_customer_customer_customer_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OrderLimit")
                        .IsRequired();
                });

            modelBuilder.Entity("Customer.Domain.Customers.Entities.CustomerEntity", b =>
                {
                    b.Navigation("CustomerOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
