namespace Authentication.Features.ViewModels;

public class AccountLoginViewModel
{
    [DefaultValue("eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjOTYxNzdiNjNjMjE0YWM5OTBiMDBhMDUwYmRjNGM1ZiIsImVtYWlsIjoiZHVuaGEzQGZ1dHVyYXNpc3RlbWFzLmNvbS5iciIsImp0aSI6IjVmM2I2ZWFmLTQyNjAtNGQyMC1hMTRkLTAwMmQzNzE1MDU1MSIsIm5iZiI6MTY2OTcyODI0NiwiaWF0IjoiMjkvMTEvMjAyMiAxMDoyNDowNiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNvbXBhbnkiLCJUZW5hbnRJZCI6ImM5NjE3N2I2M2MyMTRhYzk5MGIwMGEwNTBiZGM0YzVmIiwiRGJBbGlhcyI6InRlc3RlIiwiRGJQYXNzIjoiYWRtaW4iLCJleHAiOjE2Njk3MzE4NDYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcxNzUiLCJhdWQiOiJBdWRpZW5jZSJ9.U4dzWcMngnfRHjPGlymhhkbbGwnE8MoG0ntnv2K5Lx4F-CaR1SNac9VbcIhH6yxDbeedd6LhQeffhM_Gi9kd_g")]
    public string AccessToken { get; set; }
}